config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'shows#index'
  resources :shows do
    resources :comments
  end
  resources :venues
  resources :bands
end

app/models/show.rb
class Show < ActiveRecord::Base
  belongs_to :venue
  acts_as_mappable through: :venue

  has_many :show_bands
  has_many :bands, through: :show_bands

  has_many :comments

  validates_presence_of :datetime, :venue_id
end

app/controllers/show_controller.rb
class ShowController < ApplicationController
  include Geokit::Geocoders

  def new
    @show = Show.new
    @band = Band.new
    @venue = Venue.new
    @genre = Genre.new
  end

  def index
    @user_zip = params[:zip_code]
    if @user_zip
      # geokit docs seems to be incorrect and .join needs
      # to be used with associated tables
      @shows = Show.joins(:venue).within(25, :origin=>@user_zip).order(:datetime).page(params[:page])
    else
      @shows = Show.order(:datetime).page(params[:page])
    end
  end

  def show
    @show = Show.find(params[:id])
  end

  before_action :authenticate_user!, only: [:create, :new]
  def create
    @show = Show.new
    venue = Venue.find_or_initialize_by(name: params[:venue_name], description: params[:venue_description],
                                    street_1: params[:venue_street_1], street_2: params[:venue_street_2],
                                    city: params[:venue_city], state: params[:venue_state],
                                    zip_code: params[:venue_zip_code])
    if check_zip_code(params[:venue_zip_code])
      address = "#{venue.street_1}, #{venue.city}, #{venue.state}"
      # geokit module to convert address into longitude and latitude
      loc = MultiGeocoder.geocode(address)
      if loc.success
        venue.lat = loc.lat
        venue.lng = loc.lng
        venue.save
      end
      @show = Show.new(datetime: params[:datetime], details: params[:details], venue_id: venue.id)
      @band = Band.find_or_create_by(name: params[:band_name])
      genre = Genre.find_or_create_by(genre: params[:band_genre])
      if @band.save
        GenreBand.create(band_id: @band.id, genre_id: genre.id)
        if @show.save
          ShowBand.create(band_id: @band.id, show_id: @show.id)
          redirect_to '/shows', notice: "Show created!"
        else
          render :new
        end
      else
        render :new
      end
    else
      render :new
    end
  end

  Dotenv.load
  def check_zip_code(zip_code)
    api_key = ENV["ZIP_CODE_API_KEY"]
    zip_api_response = URI("http://www.zipcodeapi.com/rest/#{api_key}/info.json/#{zip_code}/degrees")
    response = Net::HTTP.get(zip_api_response)
    zip = JSON.parse(response)["zip_code"]
    if zip.nil?
      flash[:error] = "Invalid zip code"
    end
    !zip.nil?
  end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
  include Geokit::Geocoders

  def new
    @show = Show.new
    @band = Band.new
    @venue = Venue.new
    @genre = Genre.new
  end

  def index
    @user_zip = params[:zip_code]
    if @user_zip
      # geokit docs seems to be incorrect and .join needs
      # to be used with associated tables
      @shows = Show.joins(:venue).within(25, :origin=>@user_zip).order(:datetime).page(params[:page])
    else
      @shows = Show.order(:datetime).page(params[:page])
    end
  end

  def show
    @show = Show.find(params[:id])
    @comment = @show.comments.build
    @comments = Comment.where(show_id: @show.id)
  end

  before_action :authenticate_user!, only: [:create, :new]
  def create
    @show = Show.new
    venue = Venue.find_or_initialize_by(name: params[:venue_name], description: params[:venue_description],
                                    street_1: params[:venue_street_1], street_2: params[:venue_street_2],
                                    city: params[:venue_city], state: params[:venue_state],
                                    zip_code: params[:venue_zip_code])
    if check_zip_code(params[:venue_zip_code])
      address = "#{venue.street_1}, #{venue.city}, #{venue.state}"
      # geokit module to convert address into longitude and latitude
      loc = MultiGeocoder.geocode(address)
      if loc.success
        venue.lat = loc.lat
        venue.lng = loc.lng
        venue.save
      end
      @show = Show.new(datetime: params[:datetime], details: params[:details], venue_id: venue.id)
      @band = Band.find_or_create_by(name: params[:band_name])
      if @band.save
        get_genres.each do |genre|
          @genre = Genre.find_or_create_by(genre: genre)
          GenreBand.find_or_create_by(band_id: @band.id, genre_id: @genre.id)
        end
        if @show.save
          ShowBand.create(band_id: @band.id, show_id: @show.id)
          redirect_to shows_path, notice: "Show created!"
        else
          render :new
        end
      else
        render :new
      end
    else
      render :new
    end
  end

  private

  def get_genres
    genres = Array.new
    genres << "punk" if params["genre-punk"]
    genres << "rock" if params["genre-rock"]
    genres << "pop" if params["genre-pop"]
    genres
  end

  Dotenv.load
  def check_zip_code(zip_code)
    api_key = ENV["ZIP_CODE_API_KEY"]
    zip_api_response = URI("http://www.zipcodeapi.com/rest/#{api_key}/info.json/#{zip_code}/degrees")
    response = Net::HTTP.get(zip_api_response)
    zip = JSON.parse(response)["zip_code"]
    if zip.nil?
      flash[:error] = "Invalid zip code"
    end
    !zip.nil?
  end
end

app/helpers/show_helper.rb
module ShowHelper
end

app/views/shows/_form.html.erb
<form action='/shows/new' method='post'>
  <div>
    <label for="Band Name">Band Name</label>
    <input type='text' name='band_name' id='Band Name' placeholder='Band name'>
  </div>
  <div>
    <label for="Genre">Genre</label>
    <input type='text' name='band_genre' id='Genre' placeholder='Band genre'>
  </div>
  <div>
    <label for="Venue Name">Venue Name</label>
    <input type='text' name='venue_name' id="Venue Name" placeholder='Venue name'>
  </div>
  <div>
    <label for="Venue Description">Venue Description</label>
    <input type='text' name='venue_description' id='Venue Description' placeholder='Description'>
  </div>
  <div>
    <label for="Venue Street 1">Address 1</label>
    <input type='text' name='venue_street_1' id='Venue Street 1' placeholder='Street Address 1'>
  </div>
  <div>
    <label for="Venue Street 2">Street Address 2</label>
    <input type='text' name='venue_street_2' id='Venue Street 2' placeholder='Street Address 2'>
  </div>
  <div>
    <label for="Venue City">City</label>
    <input type='text' name='venue_city' id='Venue City' placeholder='City'>
  </div>
  <div>
    <label for="Venue State">State</label>
    <input type='text' name='venue_state' id='Venue State' placeholder='State'>
  </div>
  <div>
    <label for="Venue Zipcode">Zipcode</label>
    <input type='text' name='venue_zip_code' id='Venue Zipcode' placeholder='Zip code'>
  </div>
  <div>
    <label for="Venue Details">Venue Details</label>
    <input type='text' name='details' id='Venue Details' placeholder='Details'>
  </div>
  <div>
    <label for="Datetime">Date and Time</label>
    <input type='datetime-local' id='Datetime' name='datetime'>
  </div>
  <div>
    <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
  </div>
  <div>
    <input type='submit' value='Submit show'>
  </div>
</form>

app/views/shows/index.html.erb
<div class='row'>
  <div class='small-4 columns'>
    <div class='post-butto'n>
      <%= link_to("Tell us about your show", new_show_path ) %>
    </div>
  </div>
</div>

<div class='row'>
  <div class='small-6 columns zip-code-form'>
    Find a Show by Zip Code:
    <form action='/shows' method='get'>
      <input type='text' name='zip_code' placeholder='Zip Code'>
      <input type='submit' value='Find a Show'>
    </form>
  </div>
</div>

<div class='row'>
  <div class='small-8 columns'>
    <%= paginate @shows %>

    <% @shows.each do |show| %>
      <div class='border'>
        <% show.bands.each do |band| %>
          <div>
            <a href="/bands/<%= band.id %>"><%= band.name %></a>
          </div>
        <% end %>
        <div>
          <%= link_to("#{show.venue.name}", venue_path(show.venue)) %>
        </div>
        <div>
          <%= show.details %>
        </div>
        <div>
          <%= show.datetime %>
        </div>
        <div>
          <%= link_to("Check out this show", show_path(show)) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/shows/new.html.erb
<% if @show.errors %>
  <% @show.errors.full_messages.each do |msg| %>
    <div class='flash-error'>
      <%= msg %>
    </div>
  <% end %>
<% end %>

<% if @band.errors %>
  <% @band.errors.full_messages.each do |msg| %>
    <div class='flash-error'>
      <%= msg %>
    </div>
  <% end %>
<% end %>

<div class='row'>
  <div class='small-6 columns'>
    <form action='/shows' method='post'>
      <div>
        <label for='Band Name'>Band Name
        <input type='text' name='band_name' id='Band Name' placeholder='Band name'/></label>
      </div>
      <div>
        <label for='genre-punk'>punk
        <input type='checkbox' name='genre-punk' id='genre-punk'></label>
        <label for='genre-rock'>rock
        <input type='checkbox' name='genre-rock' id='genre-rock'></label>
        <label for='genre-pop'>pop
        <input type='checkbox' name='genre-pop' id='genre-pop'></label>
      </div>
      <div>
        <label for="Venue Name">Venue Name</label>
        <input type='text' name='venue_name' id="Venue Name" placeholder='Venue name'>
      </div>
      <div>
        <label for="Venue Description">Venue Description</label>
        <input type='text' name='venue_description' id='Venue Description' placeholder='Description'>
      </div>
      <div>
        <label for="Venue Street 1">Street Address 1</label>
        <input type='text' name='venue_street_1' id='Venue Street 1' placeholder='Street Address 1'>
      </div>
      <div>
        <label for="Venue Street 2">Street Address 2</label>
        <input type='text' name='venue_street_2' id='Venue Street 2' placeholder='Street Address 2'>
      </div>
      <div>
        <label for="Venue City">City</label>
        <input type='text' name='venue_city' id='Venue City' placeholder='City'>
      </div>
      <div>
        <label for="Venue State">State</label>
        <input type='text' name='venue_state' id='Venue State' placeholder='State'>
      </div>
      <div>
        <label for="Venue Zipcode">Zipcode</label>
        <input type='text' name='venue_zip_code' id='Venue Zipcode' placeholder='Zip code'>
      </div>
      <div>
        <label for="Venue Details">Show Details</label>
        <input type='text' name='details' id='Venue Details' placeholder='Details'>
      </div>
      <div>
        <label for="Datetime">Date and Time</label>
        <input type='datetime-local' id='Datetime' name='datetime'>
      </div>
      <div>
        <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
      </div>
      <div>
        <input type='submit' value='Submit show'>
      </div>
    </form>
  </div>
</div>

app/views/shows/show.html.erb
<div class='border'>
  <% @show.bands.each do |band| %>
    <div>
      <%= link_to(band.name, band) %>
    </div>
    Genres:
    <% band.genres.each do |genre| %>
      <div>
        <%= genre.genre %>
      </div>
    <% end %>
  <% end %>
  <div>
    <%= @show.details %>
  </div>
  <div>
    <%= @show.datetime %>
  </div>
  <div>
    <%= @show.venue.name %>
  </div>
  <div>
    <%= @show.venue.description %>
  </div>
  <div>
    <%= "#{@show.venue.street_1} #{@show.venue.street_2}" %>
  </div>
  <div>
    <%= "#{@show.venue.city}, #{@show.venue.state}" %>
  </div>
  <div>
    <%= @show.venue.zip_code %>
  </div>
</div>

<%= form_for [@show, @comment] do |f| %>
  <%= f.label :content, "Comment" %>
  <%= f.text_field :content %>
  <%= f.submit "Submit" %>
<% end %>

<% @comments.each do |comment| %>
  <div><%= comment.content %></div>
<% end %>